import { Router } from 'express';
import { authRouter } from './auth';
import { userRouter } from './users';
import { projectRouter } from './projects';
import { aiRouter } from './ai';
import { templateRouter } from './templates';
import { editorRouter } from './editor';
import { workspaceRouter } from './workspaces';
import { uploadRouter } from './upload';
import { searchRouter } from './search';
import { notificationRouter } from './notifications';
import { shareRouter } from './share';
import { versionRouter } from './versions';
import { exportRouter } from './export';
import { oauthRouter } from './oauth';
import { orgRouter } from './organizations';
import { analyticsRouter } from './analytics';
import { auditRouter } from './audit';
import { pluginRouter } from './plugins';
import { workflowRouter } from './workflows';
import { slideRouter } from './slides';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/users', userRouter);
apiRouter.use('/projects', projectRouter);
apiRouter.use('/ai', aiRouter);
apiRouter.use('/templates', templateRouter);
apiRouter.use('/editor', editorRouter);
apiRouter.use('/workspaces', workspaceRouter);
apiRouter.use('/upload', uploadRouter);
apiRouter.use('/search', searchRouter);
apiRouter.use('/notifications', notificationRouter);
apiRouter.use('/share', shareRouter);
apiRouter.use('/versions', versionRouter);
apiRouter.use('/export', exportRouter);
apiRouter.use('/oauth', oauthRouter);
apiRouter.use('/organizations', orgRouter);
apiRouter.use('/analytics', analyticsRouter);
apiRouter.use('/audit', auditRouter);
apiRouter.use('/plugins', pluginRouter);
apiRouter.use('/workflows', workflowRouter);
apiRouter.use('/slides', slideRouter);
